name: Threadfin Beta Build
on:
  push:
    branches:
      - beta
permissions:
  contents: write
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@latest
        with:
          ref: beta

      - name: Set up and Build
        uses: actions/setup-go@latest
        with:
          go-version: 1.22
        id: go
      - name: Build binaries
        run: |
          go mod tidy && go mod vendor
          bash ${GITHUB_WORKSPACE}/Utility/create_binaries.sh beta

      
      - name: Create a Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          name: Development Build
          tag_name: latest-beta

      #- name: Release
      #  uses: "marvinpinto/action-automatic-releases@latest"
      #  with:
      #    repo_token: "${{ secrets.GITHUB_TOKEN }}"
      #    automatic_release_tag: "latest-beta"
      #    prerelease: true
      #    title: "Development Build"
      #    files: dist/*
