name: Threadfin Beta Build
on:
  push:
    branches:
      - beta
permissions:
  contents: write
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          ref: beta

      - name: Set up and Build
        uses: actions/setup-go@v3
        with:
          go-version: 1.22
        id: go
      - run: bash ${GITHUB_WORKSPACE}/Utility/create_binaries.sh beta
