name: Threadfin Build
on:
  push:
    branches:
      - main
    tags: "1.*"
permissions:
  contents: write
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up and Build
        uses: actions/setup-go@v3
        with:
          go-version: 1.22
        id: go
      - name: Build Binaries
        run: bash ${GITHUB_WORKSPACE}/Utility/create_binaries.sh

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Build Setup
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v8

      - name: Docker Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          no-cache: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v8
          tags: fyb3roptik/threadfin:latest,fyb3roptik/threadfin:${{  github.ref_name }}

      - name: Docker Nvidia Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: NVIDIA=1
          push: true
          no-cache: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v8
          tags: fyb3roptik/threadfin:latest-nvidia,fyb3roptik/threadfin:${{  github.ref_name }}-nvidia

      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: dist/*